# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0002_auto_20170518_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('halfs_block', wagtail.wagtailcore.blocks.StructBlock([(b'photo', wagtail.wagtailimages.blocks.ImageChooserBlock(classname='img', required=True)), (b'title', wagtail.wagtailcore.blocks.CharBlock(classname='title', required=True)), (b'content', wagtail.wagtailcore.blocks.RichTextBlock(classname='content', required=True))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
    ]
