# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 23:56
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170518_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('halfs_block', wagtail.wagtailcore.blocks.StructBlock([(b'photo', wagtail.wagtailimages.blocks.ImageChooserBlock(classname='img', required=True)), (b'title', wagtail.wagtailcore.blocks.CharBlock(classname='title', required=True)), (b'text', wagtail.wagtailcore.blocks.RichTextBlock(classname='text-content'))]))]),
        ),
    ]
