# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('home', '0013_auto_20170521_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('top', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('middle', wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('halves_block', wagtail.wagtailcore.blocks.StructBlock([(b'one_of_two', wagtail.wagtailcore.blocks.StructBlock([('photo', wagtail.wagtailimages.blocks.ImageChooserBlock(classname='img')), ('title', wagtail.wagtailcore.blocks.CharBlock(classname='title', required=True)), ('text', wagtail.wagtailcore.blocks.RichTextBlock())])), (b'two_of_two', wagtail.wagtailcore.blocks.StructBlock([('photo', wagtail.wagtailimages.blocks.ImageChooserBlock(classname='img')), ('title', wagtail.wagtailcore.blocks.CharBlock(classname='title', required=True)), ('text', wagtail.wagtailcore.blocks.RichTextBlock())]))], classname='full title')), ('person', wagtail.wagtailcore.blocks.StructBlock([(b'first_name', wagtail.wagtailcore.blocks.CharBlock(classname='fname', required=True)), (b'surname', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'photo', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'biography', wagtail.wagtailcore.blocks.RichTextBlock())])), ('list', wagtail.wagtailcore.blocks.StructBlock([(b'list_title', wagtail.wagtailcore.blocks.CharBlock(classname='bloat_fork')), (b'list_item', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([('ingredient', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('amount', wagtail.wagtailcore.blocks.CharBlock())])))])), ('thirds', wagtail.wagtailcore.blocks.StructBlock([(b'thirds_heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), (b'one_of_three', wagtail.wagtailcore.blocks.StreamBlock([('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('person', wagtail.wagtailcore.blocks.StructBlock([(b'first_name', wagtail.wagtailcore.blocks.CharBlock(classname='fname', required=True)), (b'surname', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'photo', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'biography', wagtail.wagtailcore.blocks.RichTextBlock())])), ('drink', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('tea', 'Tea'), ('coffee', 'Coffee')]))])), (b'two_of_three', wagtail.wagtailcore.blocks.StreamBlock([('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('person', wagtail.wagtailcore.blocks.StructBlock([(b'first_name', wagtail.wagtailcore.blocks.CharBlock(classname='fname', required=True)), (b'surname', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'photo', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'biography', wagtail.wagtailcore.blocks.RichTextBlock())]))])), (b'three_of_three', wagtail.wagtailcore.blocks.StreamBlock([('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('person', wagtail.wagtailcore.blocks.StructBlock([(b'first_name', wagtail.wagtailcore.blocks.CharBlock(classname='fname', required=True)), (b'surname', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'photo', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'biography', wagtail.wagtailcore.blocks.RichTextBlock())]))]))]))])),
                ('bottom', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
