# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_servicepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicePage',
            new_name='TemplatePage',
        ),
    ]
